title: Reci
highlighter: pygments
markdown: redcarpet
extensions: [no_fenced_code_blocks]
extensions: [tables]
paginate: 8
permalink: /:categories/:title
url: http://recitativa.github.com
timezone: Asia/Shanghai
custom_css: true
